


export default [
  { name: 'Mohammed Shaaban', origin: 'Egypt', p: 'midfield' },
  { name: 'Mohammed Abdel Fattah', origin: 'Egypt', p: 'defence' },
  { name: 'Ahmed Tawfik', origin: 'Egypt', p: 'midfield' },
  { name: 'Ahmed Samir Farag', origin: 'Egypt', p: 'midfield' },
  { name: 'Ahmed Eid Abdel Malek', origin: 'Egypt', p: 'midfield' },
  { name: 'Essam El-Hadary', origin: 'Egypt', p: 'goalkeep' },
  { name: 'Ahmed Dowidar', origin: 'Egypt', p: 'defence' },
  { name: 'Moamen Zakaria', origin: 'Egypt', p: 'midfield' },
  { name: 'Mahmoud Hassan', origin: 'Egypt', p: 'midfield' },
  { name: 'Ahmed Samir', origin: 'Egypt', p: 'midfield' },
  { name: 'Ahmed Daouda', origin: 'Egypt', p: 'midfield' },
  { name: 'Mahmoud Fathalia', origin: 'Egypt', p: 'defence' },
  { name: 'Emad Moteab', origin: 'Egypt', p: 'forward' },
  { name: 'Khaled Kamar', origin: 'Egypt', p: 'forward' },
  { name: 'Saleh Gomaa', origin: 'Egypt', p: 'midfield' },
  { name: 'Milo', origin: 'Egypt', p: 'defence' },
  { name: 'Ahmed Hegazi', origin: 'Egypt', p: 'defence' },
  { name: 'El Sayed Hamdy', origin: 'Egypt', p: 'forward' },
  { name: 'Ali Gabr', origin: 'Egypt', p: 'defence' },
  { name: 'Ali Lotfi', origin: 'Egypt', p: 'goalkeep' },
  { name: 'Abdallah Said', origin: 'Egypt', p: 'forward' },
  { name: 'Ramy Rabia', origin: 'Egypt', p: 'midfield' },
  { name: 'Mohamed Salah', origin: 'Egypt', p: 'midfield' },
  { name: 'Ahmed Gaafar', origin: 'Egypt', p: 'forward' },
  { name: 'Walid Soliman', origin: 'Egypt', p: 'midfield' },
  { name: 'Basem Ali', origin: 'Egypt', p: 'defence' },
  { name: 'Ahmed El-Shenawy', origin: 'Egypt', p: 'goalkeep' },

  { name: 'Mounir Obbadi', origin: 'Morocco', p: 'midfield' },
  { name: 'Zakaria Hadraf', origin: 'Morocco', p: 'midfield' },
  { name: 'Rachid Alioui', origin: 'Morocco', p: 'forward' },
  { name: 'Fouad Chafik', origin: 'Morocco', p: 'defence' },
  { name: 'Walid El Karti', origin: 'Morocco', p: 'midfield' },
  { name: 'Yassine Jebbour', origin: 'Morocco', p: 'defence' },
  { name: 'Ayoub El Khaliqi', origin: 'Morocco', p: 'defence' },
  { name: 'Nabil Dirar', origin: 'Morocco', p: 'midfield' },
  { name: 'Rochdi Achenteh', origin: 'Morocco', p: 'defence' },
  { name: 'Abdelatif Noussir', origin: 'Morocco', p: 'defence' },
  { name: 'Nabil El Zhar', origin: 'Morocco', p: 'midfield' },
  { name: 'Hamza Abourrouzouk', origin: 'Morocco', p: 'forward' },
  { name: 'Chazir Belghazouani', origin: 'Morocco', p: 'midfield' },
  { name: 'Karim El Ahmadi', origin: 'Morocco', p: 'midfield' },
  { name: 'Achraf Lazaar', origin: 'Morocco', p: 'defence' },
  { name: 'Adel Taarabt', origin: 'Morocco', p: 'midfield' },
  { name: 'Ahmed El Messaoudi', origin: 'Morocco', p: 'defence' },
  { name: 'Salaheddine Aqqal', origin: 'Morocco', p: 'midfield' },
  { name: 'Nadir Lamyaghri', origin: 'Morocco', p: '' },
  { name: 'Mounir El Hamdaoui', origin: 'Morocco', p: 'forward' },
  { name: 'Jawad El Hajri', origin: 'Morocco', p: 'forward' },
  { name: 'Munir Mohand', origin: 'Morocco', p: 'goalkeep' },
  { name: 'Ahmed Kantari', origin: 'Morocco', p: 'defence' },
  { name: 'Karim Fegrouche', origin: 'Morocco', p: 'defence' },
  { name: 'Yacine Bammou', origin: 'Morocco', p: 'forward' },
  { name: 'Anaz Zniti', origin: 'Morocco', p: 'goalkeep' },

  { name: 'Raheem Adewole', origin: 'Nigeria', p: 'midfield' },
  { name: 'Ahmed Musa', origin: 'Nigeria', p: 'forward' },
  { name: 'Henry Uche', origin: 'Nigeria', p: 'midfield' },
  { name: 'Daniel Akpeyi', origin: 'Nigeria', p: 'goalkeep' },
  { name: 'Victor Moses', origin: 'Nigeria', p: 'midfield' },
  { name: 'Gbolahan Salami', origin: 'Nigeria', p: 'forward' },
  { name: 'Hope Akpan', origin: 'Nigeria', p: 'midfield' },
  { name: 'Ugonna Uzochukwu', origin: 'Nigeria', p: 'defence' },
  { name: 'Christian Pyagbara', origin: 'Nigeria', p: 'forward' },
  { name: 'Victor Obinna', origin: 'Nigeria', p: 'forward' },
  { name: 'Osas Omomo', origin: 'Nigeria', p: 'defence' },
  { name: 'Bright Esieme', origin: 'Nigeria', p: 'defence' },
  { name: 'Sone Aluko', origin: 'Nigeria', p: 'forward' },
  { name: 'Oladapo Olufemi', origin: 'Nigeria', p: 'midfield' },
  { name: 'Nnamdi Oduamadi', origin: 'Nigeria', p: 'forward' },
  { name: 'Chima Akas', origin: 'Nigeria', p: 'defence' },
  { name: 'Kunle Odunlami', origin: 'Nigeria', p: 'defence' },
  { name: 'Kingsley Sokari', origin: 'Nigeria', p: '' },
  { name: 'Stanley Dimbga', origin: 'Nigeria', p: 'midfield' },
  { name: 'Nosa Igiebor', origin: 'Nigeria', p: 'midfield' },
  { name: 'Mohammed Gambo', origin: 'Nigeria', p: 'forward' },
  { name: 'Joseph Akpala', origin: 'Nigeria', p: 'forward' },
  { name: 'Ugonna Anyora', origin: 'Nigeria', p: 'midfield' },
  { name: 'Oghenekaro', origin: 'Nigeria', p: 'forward' },
  { name: 'Harry Ifeanyi', origin: 'Nigeria', p: 'defence' },

  { name: 'Emile Paul', origin: 'Senegal', p: 'forward' },
  { name: 'Makhtar', origin: 'Senegal', p: 'midfield' },
  { name: 'Mamadou Ba', origin: 'Senegal', p: 'goalkeep' },
  { name: 'Mohammed Daf', origin: 'Senegal', p: 'midfield' },
  { name: 'Christophe Diedhiou', origin: 'Senegal', p: 'defence' },
  { name: 'Stephane Badji', origin: 'Senegal', p: 'midfield' },
  { name: 'Victor Demba', origin: 'Senegal', p: 'defence' },
  { name: 'Demba Ba', origin: 'Senegal', p: 'forward' },
  { name: 'Jacques Faty', origin: 'Senegal', p: 'defence' },
  { name: "Dame N'Doye", origin: 'Senegal', p: 'forward' },
  { name: 'Kader Mangane', origin: 'Senegal', p: 'defence' },
  { name: "Khadim N'Diaye", origin: 'Senegal', p: 'goalkeep' },
  { name: 'Bouna Coundoul', origin: 'Senegal', p: 'goalkeep' },
  { name: 'Moussa Ndione', origin: 'Senegal', p: 'midfield' },
  { name: 'Famara Diedhiou', origin: 'Senegal', p: 'forward' },
  { name: 'Moustapha Bayal', origin: 'Senegal', p: 'defence' },
  { name: 'Khouma Babacar', origin: 'Senegal', p: 'forward' },
  { name: 'Abdoulaye Ba', origin: 'Senegal', p: 'defence' },
  { name: 'Adama Mbengue', origin: 'Senegal', p: 'midfield' },
  { name: "Mamadou N'Diaye", origin: 'Senegal', p: 'defence' },
  { name: 'Diawandou Diagne', origin: 'Senegal', p: 'defence' },
  { name: 'Lamine Gassama', origin: 'Senegal', p: 'defence' },
  { name: 'Papa Gueye', origin: 'Senegal', p: 'defence' },
  { name: 'Papa Demba Camara', origin: 'Senegal', p: 'goalkeep' },
  { name: 'Amara Baby', origin: 'Senegal', p: 'midfield' },
  { name: 'Sangone', origin: 'Senegal', p: 'forward' },

  { name: 'Issam Jemaa', origin: 'Tunisia', p: 'forward' },
  { name: 'Ahmed Akaichi', origin: 'Tunisia', p: 'forward' },
  { name: 'Samil Allagui', origin: 'Tunisia', p: 'forward' },
  { name: 'Youssef Msakni', origin: 'Tunisia', p: 'midfield' },
  { name: 'Khalil Chemmam', origin: 'Tunisia', p: 'defence' },
  { name: 'Mossaab Sassi', origin: 'Tunisia', p: 'midfield' },
  { name: 'Yassine Chikhaoui', origin: 'Tunisia', p: 'midfield' },
  { name: 'Lassad Jaziri', origin: 'Tunisia', p: 'forward' },
  { name: 'Wissem Ben Yahia', origin: 'Tunisia', p: 'midfield' },
  { name: 'Ahmed Belaid', origin: 'Tunisia', p: 'midfield' },
  { name: 'Khaled Souissi', origin: 'Tunisia', p: 'defence' },
  { name: 'stephane Nater', origin: 'Tunisia', p: 'midfield' },
  { name: 'Aymen Abdennour', origin: 'Tunisia', p: 'defence' },
  { name: 'Mohamed Yacoubi', origin: 'Tunisia', p: 'defence' },
  { name: 'Haythem Jouini', origin: 'Tunisia', p: 'forward' },
  { name: 'Hatten Baratti', origin: 'Tunisia', p: 'midfield' },
  { name: 'Oussama Haddadi', origin: 'Tunisia', p: 'defence' },
  { name: 'Ammar Jemal', origin: 'Tunisia', p: 'defence' },
  { name: 'Aymen Mathlouthi', origin: 'Tunisia', p: 'goalkeep' },
  { name: 'Bilel Mohsni', origin: 'Tunisia', p: 'defence' },
  { name: 'Hamdi Harbaoui', origin: 'Tunisia', p: 'defence' },

  { name: 'Mathew Ryan', origin: 'Australia', p: 'goalkeep' },
  { name: 'Mitchell Langerak', origin: 'Australia', p: 'goalkeep' },
  { name: 'Danny Vukovic', origin: 'Australia', p: 'goalkeep' },
  { name: 'Milos Degenek', origin: 'Australia', p: 'defence' },
  { name: 'Alex Gersbach', origin: 'Australia', p: 'defence' },
  { name: 'Matthew Jurman', origin: 'Australia', p: 'defence' },
  { name: 'Bailey Wright', origin: 'Australia', p: 'defence' },
  { name: 'Josh Risdon', origin: 'Australia', p: 'defence' },
  { name: 'Aziz Behich', origin: 'Australia', p: 'defence' },
  { name: 'Ryan McGowan', origin: 'Australia', p: 'defence' },
  { name: 'Trent Sainsbury', origin: 'Australia', p: 'defence' },
  { name: 'Mark Milligan', origin: 'Australia', p: 'midfield' },
  { name: 'Aaron Mooy', origin: 'Australia', p: 'midfield' },
  { name: 'James Troisi', origin: 'Australia', p: 'midfield' },
  { name: 'Mile Jedinak', origin: 'Australia', p: 'midfield' },
  { name: 'Massimo Loungo', origin: 'Australia', p: 'midfield' },
  { name: 'Jackson Irvine', origin: 'Australia', p: 'midfield' },
  { name: 'Tom Rogic', origin: 'Australia', p: 'midfield' },
  { name: 'Tim Cahill', origin: 'Australia', p: 'forward' },
  { name: 'Mathew Leckie', origin: 'Australia', p: 'forward' },
  { name: 'Tomi Juric', origin: 'Australia', p: 'forward' },
  { name: 'Robbie Kruse', origin: 'Australia', p: 'forward' },
  { name: 'Nikita Rukavytsya', origin: 'Australia', p: 'forward' },

  { name: 'Alireza Beiranvand', origin: 'IR Iran', p: 'goalkeep' },
  { name: 'Mohammad Rashid', origin: 'IR Iran', p: 'goalkeep' },
  { name: 'Amir Abedzadeh', origin: 'IR Iran', p: 'goalkeep' },
  { name: 'Vouria Ghafouri', origin: 'IR Iran', p: 'defence' },
  { name: 'Jalal Hosseini', origin: 'IR Iran', p: 'defence' },
  { name: 'Milad Mohammadi', origin: 'IR Iran', p: 'defence' },
  { name: 'Morteza Pouraliganji', origin: 'IR Iran', p: 'defence' },
  { name: 'Ramin Razaeian', origin: 'IR Iran', p: 'defence' },
  { name: 'Rouzbeh Cheshmi', origin: 'IR Iran', p: 'defence' },
  { name: 'Saeid Aghaei', origin: 'IR Iran', p: 'defence' },
  { name: 'Ehsan Hajsafi', origin: 'IR Iran', p: 'midfield' },
  { name: 'Saeid Ezatolahi', origin: 'IR Iran', p: 'midfield' },
  { name: 'Saman Ghoddos', origin: 'IR Iran', p: 'midfield' },
  { name: 'Omid Ebrahimi', origin: 'IR Iran', p: 'midfield' },
  { name: 'Vahid Amiri', origin: 'IR Iran', p: 'midfield' },
  { name: 'Ali Kamiri', origin: 'IR Iran', p: 'midfield' },
  { name: 'Akbar Imani', origin: 'IR Iran', p: 'midfield' },
  { name: 'Alireza Jahanbaksh', origin: 'IR Iran', p: 'midfield' },
  { name: 'Ashkan Dejagah', origin: 'IR Iran', p: 'midfield' },
  { name: 'Ahmad Abdollahzadeh', origin: 'IR Iran', p: 'midfield' },
  { name: 'Mehdi Torabi', origin: 'IR Iran', p: 'midfield' },
  { name: 'Karim Ansarifard', origin: 'IR Iran', p: 'forward' },
  { name: 'Reza Ghoochannejhad', origin: 'IR Iran', p: 'forward' },
  { name: 'Medhi Taremi', origin: 'IR Iran', p: 'forward' },
  { name: 'Keveh Rezaei', origin: 'IR Iran', p: 'forward' },
  { name: 'Sardar Azmoun', origin: 'IR Iran', p: 'forward' },

  { name: 'Masaaki Higashiguchi', origin: 'Japan', p: 'goalkeep' },
  { name: 'Shūichi Gonda', origin: 'Japan', p: 'goalkeep' },
  { name: 'Kōsuke Nakamura', origin: 'Japan', p: 'goalkeep' },
  { name: 'Gen Shōji', origin: 'Japan', p: 'defence' },
  { name: 'Shōgo Taniguchi', origin: 'Japan', p: 'defence' },
  { name: 'Shintarō Kurumaya', origin: 'Japan', p: 'defence' },
  { name: 'Genta Miura', origin: 'Japan', p: 'defence' },
  { name: 'Ryō Hatsuse', origin: 'Japan', p: 'defence' },
  { name: 'Sei Muroya', origin: 'Japan', p: 'defence' },
  { name: 'Shūto Yamamoto', origin: 'Japan', p: 'defence' },
  { name: 'Naomichi Ueda', origin: 'Japan', p: 'defence' },
  { name: 'Yōsuke Ideguchi', origin: 'Japan', p: 'midfield' },
  { name: 'Yōjiro Takahagi', origin: 'Japan', p: 'midfield' },
  { name: 'Ryota Oshima', origin: 'Japan', p: 'midfield' },
  { name: 'Shoma Doi', origin: 'Japan', p: 'midfield' },
  { name: 'Kento Misao', origin: 'Japan', p: 'midfield' },
  { name: 'Yasuyuki Konno', origin: 'Japan', p: 'midfield' },
  { name: 'Shū Kurata', origin: 'Japan', p: 'forward' },
  { name: 'Kengo Kawamata', origin: 'Japan', p: 'forward' },
  { name: 'Yu Kobayashi', origin: 'Japan', p: 'forward' },
  { name: "Jun'ya Itō", origin: 'Japan', p: 'forward' },
  { name: 'Mū Kanazaki', origin: 'Japan', p: 'forward' },
  { name: 'Hiroyuki Abe', origin: 'Japan', p: 'forward' },

  { name: 'Kim Seung-gyu', origin: 'Korea Republic', p: 'goalkeep' },
  { name: 'Cho Hyun-woo', origin: 'Korea Republic', p: 'goalkeep' },
  { name: 'Kim Dong-jun', origin: 'Korea Republic', p: 'goalkeep' },
  { name: 'Kim Young-gwon', origin: 'Korea Republic', p: 'defence' },
  { name: 'Jang Hyun-soo', origin: 'Korea Republic', p: 'defence' },
  { name: 'Kim Jin-su', origin: 'Korea Republic', p: 'defence' },
  { name: 'Go Yo-han', origin: 'Korea Republic', p: 'defence' },
  { name: 'Hong Chul', origin: 'Korea Republic', p: 'defence' },
  { name: 'Choi Chul-soon', origin: 'Korea Republic', p: 'defence' },
  { name: 'Yun Young-sun', origin: 'Korea Republic', p: 'defence' },
  { name: 'Kim Min-jae', origin: 'Korea Republic', p: 'defence' },
  { name: 'Jung Seung-hyun', origin: 'Korea Republic', p: 'defence' },
  { name: 'Lee Keun-ho', origin: 'Korea Republic', p: 'midfield' },
  { name: 'Lee Jae-sung', origin: 'Korea Republic', p: 'midfield' },
  { name: 'Jung Woo-young', origin: 'Korea Republic', p: 'midfield' },
  { name: 'Lee Seung-gi', origin: 'Korea Republic', p: 'midfield' },
  { name: 'Kim Tae-hwan', origin: 'Korea Republic', p: 'midfield' },
  { name: 'Lee Chang-min', origin: 'Korea Republic', p: 'midfield' },
  { name: 'Kim Seung-dae', origin: 'Korea Republic', p: 'midfield' },
  { name: 'Kim Sung-joon', origin: 'Korea Republic', p: 'midfield' },
  { name: 'Lee Chan-dong', origin: 'Korea Republic', p: 'midfield' },
  { name: 'Son Jun-ho', origin: 'Korea Republic', p: 'midfield' },
  { name: 'Kim Shin-wook', origin: 'Korea Republic', p: 'forward' },
  { name: 'Jin Seong-wook', origin: 'Korea Republic', p: 'forward' },

  { name: 'Moslem Al-Furayj', origin: 'Saudi Arabia', p: 'goalkeep' },
  { name: 'Abdulquddus Atiah', origin: 'Saudi Arabia', p: 'goalkeep' },
  { name: 'Assaf Al-Qarni', origin: 'Saudi Arabia', p: 'goalkeep' },
  { name: 'Salem Ali Yahya', origin: 'Saudi Arabia', p: 'defence' },
  { name: 'Abdullah Al-Shammari', origin: 'Saudi Arabia', p: 'defence' },
  { name: 'Mohammed Al-Khabrani', origin: 'Saudi Arabia', p: 'defence' },
  { name: 'Omar Hawsawi', origin: 'Saudi Arabia', p: 'defence' },
  { name: 'Abdurahman Al-Obaid', origin: 'Saudi Arabia', p: 'defence' },
  { name: 'Sultan Al-Ghanam', origin: 'Saudi Arabia', p: 'defence' },
  { name: 'Hammam Ajaj', origin: 'Saudi Arabia', p: 'defence' },
  { name: 'Abdullah Al-Ammar', origin: 'Saudi Arabia', p: 'defence' },
  { name: 'Nooh Al-Mousa', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Salman Al-Moasher', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Naif Hazazi', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Hattan Bahebri', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Maan Khodari', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Mohamed Kanno', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Ahmed Al-Fraidi', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Ahmed Al-Fiqi', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Jaber Mustafa', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Khalid Kaabi', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Saleh Al-Amri', origin: 'Saudi Arabia', p: 'midfield' },
  { name: 'Ali Al-Nemer', origin: 'Saudi Arabia', p: 'forward' },
  { name: 'Mukhtar Fallatah', origin: 'Saudi Arabia', p: 'forward' },

  { name: 'Thibaut Courtois', origin: 'Belgium', p: 'goalkeep' },
  { name: 'Simon Mignolet', origin: 'Belgium', p: 'goalkeep' },
  { name: 'Koen Casteels', origin: 'Belgium', p: 'goalkeep' },


  { name: 'Laurent Depoitre', origin: 'Belgium', p: 'goalkeep' },
  { name: 'Divock Origi', origin: 'Belgium', p: 'forward' },
  { name: 'Romelu Lukaku', origin: 'Belgium', p: 'forward' },

  { name: 'Ricardo Ferreira', origin: 'Portugal', p: 'forward' },
  { name: 'Ricardo Quaresma', origin: 'Portugal', p: 'forward' },
  { name: 'Nani', origin: 'Portugal', p: 'forward' },
  { name: 'Renato Sanches', origin: 'Portugal', p: 'forward' },
  { name: 'João Moutinho', origin: 'Portugal', p: 'forward' },
  { name: 'Olivier Giroud', origin: 'France', p: 'forward' },
  { name: 'Kevin Gameiro', origin: 'France', p: 'forward' },
  { name: 'Paul Pogba', origin: 'France', p: 'midfield' },
  { name: 'Thomas Lemar', origin: 'France', p: 'midfield' },
  { name: 'Hugo Lloris', origin: 'France', p: 'goalkeep' },
  { name: 'Igor Akinfeev', origin: 'Russia', p: 'goalkeep' },
  { name: 'Dmitri Kombarov', origin: 'Russia', p: 'midfield' },
  { name: 'Viktor Vasin', origin: 'Russia', p: 'defence' },
  { name: 'Anton Zabolotny', origin: 'Russia', p: 'forward' },
  { name: 'Danny Welbeck', origin: 'England', p: 'forward' },
  { name: 'Jermain Defoe', origin: 'England', p: 'forward' },
  { name: 'Fabian Delph', origin: 'England', p: 'midfield' },
  { name: 'Luke Shaw', origin: 'England', p: 'defence' },
  { name: 'Fraser Forster', origin: 'England', p: 'goalkeep' },
  { name: 'Raheem Sterling', origin: 'England', p: 'midfield' },


  { name: 'Diego Costa', origin: 'Spain', p: 'forward' },
  { name: 'David Villa', origin: 'Spain', p: 'forward' },
  { name: 'Álvaro Morata', origin: 'Spain', p: 'forward' },
  { name: 'Andrés Iniesta', origin: 'Spain', p: 'midfield' },
  { name: 'Thiago', origin: 'Spain', p: 'midfield' },
  { name: 'Marco Asensio', origin: 'Spain', p: 'midfield' },
  { name: 'Gerard Piqué', origin: 'Spain', p: 'midfield' },
  { name: 'Manuel Neuer', origin: 'Germany', p: 'goalkeep' },
  { name: 'Thomas Müller', origin: 'Germany', p: 'forward' },
  { name: 'Sandro Wagner', origin: 'Germany', p: 'forward' },
  { name: 'Kevin Trapp', origin: 'Germany', p: 'goalkeep' },
  { name: 'Mesut Özil', origin: 'Germany', p: 'midfield' },
  { name: 'Matthias Ginter', origin: 'Germany', p: 'defence' },
  { name: 'Marcel Halstenberg', origin: 'Germany', p: 'defence' },
  { name: 'Luka Modrić', origin: 'Croatia', p: 'midfield' },
  { name: 'Mario Pašalić', origin: 'Croatia', p: 'midfield' },
  { name: 'Nikola Kalinić', origin: 'Croatia', p: 'forward' },
  { name: 'Ivan Perišić', origin: 'Croatia', p: 'midfield' },

];




const t =[
  "Egypt",
  "Morocco",
  "Nigeria",
  "Senegal",
  "Tunisia",
  "Australia",
  "IR Iran",
  "Japan",
  "Korea Republic",
  "Saudi Arabia",
  "Belgium",
  "Croatia",
  "Denmark",
  "England",
  "France",
  "Germany",
  "Iceland",
  "Poland",
  "Portugal",
  "Russia",
  "Serbia",
  "Spain",
  "Sweden",
  "Switzerland",
  "Costa Rica",
  "Mexico",
  "Panama",
];
